services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile

    image: orangehrm-ui-tests

    container_name: orangehrm-regression

    working_dir: /usr/workspace

    volumes:
      - .:/usr/workspace

    command: >
      /bin/sh -c
      "ls -la &&
       pytest -sv --alluredir=allure-results"

    environment:
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
